<?php
// Add new input type "section"
if ( function_exists('smile_add_input_type'))
{
	smile_add_input_type('section' , 'section_settings_field' );
}

/**
* Function to handle new input type "section"
*
* @param $settings		- settings provided when using the input type "section"
* @param $value			- holds the default / updated value
* @return string/html 	- html output generated by the function
*/
function section_settings_field($name, $settings, $value)
{
	$input_name = $name;
	$title = isset($settings['title']) ? $settings['title'] : '';
	$output = '<div class="section-title">';
	$output .= $title;
	$output .= '</div>';
	return $output;
}